name: Create Release

on:
# TODO uncomment below code before pr
  # schedule:
  #   - cron: "*/30 * * * *" # every 30 minutes
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release to cut (e.g. 1.2.3). No leading v"
        required: false
      force:
        description: "Release stack even if change validator does not detect changes, or a package is removed"
        required: true
        type: choice
        default: "false"
        options:
          - "true"
          - "false"

concurrency: release
env:
  UBI_BUILD_SHA256_FILENAME: build.oci.sha256
  UBI_RUN_SHA256_FILENAME: run.oci.sha256
  UBI_RUN_NODEJS_16_SHA256_FILENAME: run-nodejs-16.oci.sha256
  UBI_RUN_NODEJS_18_SHA256_FILENAME: run-nodejs-18.oci.sha256
  UBI_RUN_NODEJS_20_SHA256_FILENAME: run-nodejs-20.oci.sha256
  UBI_RUN_JAVA_8_SHA256_FILENAME: run-java-8.oci.sha256
  UBI_RUN_JAVA_11_SHA256_FILENAME: run-java-11.oci.sha256
  UBI_RUN_JAVA_17_SHA256_FILENAME: run-java-17.oci.sha256
  UBI_RUN_JAVA_21_SHA256_FILENAME: run-java-21.oci.sha256

  RECEIPT_FILENAME_SUFFIX: "receipt.cyclonedx.json"
  STACKS_FILENAME: "images.json"

jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-22.04
    outputs:
      stacks: ${{ steps.get-stack-names.outputs.stacks }}
      support_usns: ${{ steps.get-stack-names.outputs.support_usns }}
      github_repo_name: ${{ steps.repo.outputs.github_repo_name }}
      registry_repo_name: ${{ steps.repo.outputs.registry_repo_name }}
      repo_owner: ${{ steps.repo.outputs.repo_owner }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get stack names and USN support
        id: get-stack-names
        run: |
          stacks=$(
            cat <<EOF
          [
            {
              "name": "stack",
              "config_dir": "stack",
              "output_dir": "build",
              "build_image": "build",
              "build_receipt_filename": "build",
              "run_image": "run",
              "run_receipt_filename": "run",
              "patched_usns_filename_suffix": "patched-usns.json",
              "create_build_image": true
            }
          ]
          EOF
          )

          support_usns=true

          if [[ -f ${{ env.STACKS_FILENAME }} ]]; then
            stacks=$(jq '[.images[] |
            . +
            {
              "create_build_image": (.create_build_image // false)
            }]' ${{ env.STACKS_FILENAME }} )

            support_usns=$( jq '.support_usns' ${{ env.STACKS_FILENAME }} )
          fi

          stacks=$(jq -c <<< "$stacks" )
          printf "stacks=%s\n" "${stacks}" >> "$GITHUB_OUTPUT"
          printf "support_usns=%s\n" "${support_usns}" >> "$GITHUB_OUTPUT"

      - name: Get Repository Name
        id: repo
        run: |
          full=${{ github.repository }}
          # Strip off the org and slash from repo name
          # paketo-buildpacks/jammy-base-stack --> jammy-base-stack
          repo=$(echo "${full}" | sed 's/^.*\///')
          echo "github_repo_name=${repo}" >> "$GITHUB_OUTPUT"

          # Strip off 'stack' suffix from repo name
          # paketo-buildpacks/jammy-base-stack --> jammy-base
          registry_repo="${repo//-stack/}"
          echo "registry_repo_name=${registry_repo}" >> "$GITHUB_OUTPUT"

          # translates 'paketo-buildpacks' to 'paketobuildpacks'
          repo_owner="${GITHUB_REPOSITORY_OWNER/-/}"
          printf "repo_owner=%s\n" "${repo_owner}" >> "$GITHUB_OUTPUT"

  poll_ubi_images:
    name: Poll UBI Images
    runs-on: ubuntu-22.04
    needs: preparation
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    outputs:
      ubi_images_need_update: ${{ steps.compare_previous_and_current_sha256_hash_codes.outputs.ubi_images_need_update }}
    steps:
      - name: Find and Download Previous build image hash code of stack ${{ matrix.stacks.build_image }}
        if: ${{ matrix.stacks.create_build_image == true }}
        uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
        with:
          asset_pattern: "${{ matrix.stacks.build_image }}.oci.sha256"
          search_depth: 1
          repo: ${{ github.repository }}
          output_path: "/github/workspace/previous_${{ matrix.stacks.build_image }}.oci.sha256"
          token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

      - name: Find and Download Previous run image hash code of stack ${{ matrix.stacks.run_image }}
        uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
        with:
          asset_pattern: "${{ matrix.stacks.run_image }}.oci.sha256"
          search_depth: 1
          repo: ${{ github.repository }}
          output_path: "/github/workspace/previous_${{ matrix.stacks.run_image }}.oci.sha256"
          token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

      - name: Treeee
        run: tree .

      - name: Get current run image hascode of stack ${{ matrix.stacks.name }}
        run: |
          skopeo inspect --format "{{.Digest}}" ${{ matrix.stacks.run_image_registry }} > current_${{ matrix.stacks.run_image }}.oci.sha256

      - name: Get current build image hascode of stack ${{ matrix.stacks.name }}
        if: ${{ matrix.stacks.create_build_image == true }}
        run: |
          skopeo inspect --format "{{.Digest}}" ${{ matrix.stacks.build_image_registry }} > current_${{ matrix.stacks.build_image }}.oci.sha256

      - name: Treeee
        run: tree .

      - name: Compare previous and current hash codes
        id: compare_previous_and_current_sha256_hash_codes
        run: |
          if [ "$(cat previous_${{ matrix.stacks.run_image }}.oci.sha256)" != "$(cat current_${{ matrix.stacks.run_image }}.oci.sha256)" ]; then
            echo "ubi_images_need_update=true" >> "$GITHUB_OUTPUT"
          fi

          if [ "${{ matrix.stacks.create_build_image }}" == "true" ]; then

            if [ "$(cat previous_${{ matrix.stacks.build_image }}.oci.sha256)" != "$(cat current_${{ matrix.stacks.build_image }}.oci.sha256)" ]; then
              echo "ubi_images_need_update=true" >> "$GITHUB_OUTPUT"
            fi
          fi

  stack_files_changed:
    name: Determine If Stack Files Changed
    runs-on: ubuntu-22.04
    needs: [ poll_ubi_images, preparation ] 
    if: ${{ ! ( needs.poll_ubi_images.outputs.ubi_images_need_update == null &&  github.event_name == 'schedule' ) }}
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    outputs:
      stack_files_changed: ${{ steps.compare.outputs.stack_files_changed }}
    steps:
    - name: Checkout With History
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # gets full history

    - name: Compare With Previous Release
      id: compare
      run: |
        # shellcheck disable=SC2046
        changed="$(git diff --name-only $(git describe --tags --abbrev=0) -- ${{ matrix.stacks.config_dir }})"
        if [ -n "${changed}" ]
        then
          echo "Relevant files of ${{ matrix.stacks.name }}, have changed since previous release."
          echo "${changed}"
          echo "stack_files_changed=true" >> "$GITHUB_OUTPUT"
        fi

  run_if_stack_files_changed:
    name: Run If Stack Files Changed
    runs-on: ubuntu-22.04
    needs: [stack_files_changed]
    if: ${{ needs.stack_files_changed.outputs.stack_files_changed == 'true' }}
    steps:
    - name: Run if stack files changed
      run: |
        echo "stack files have changed"

  create_stack:
    name: Create Stack
    needs: [ poll_ubi_images, preparation ] 
    if: ${{ ! ( needs.poll_ubi_images.outputs.ubi_images_need_update == null &&  github.event_name == 'schedule' ) }}
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # TODO remove before PR
    - name: Tree
      run: tree .

    - name: Create stack ${{ matrix.stacks.name }}
      id: create-stack
      run: |
        scripts/create.sh --stack-dir ${{ matrix.stacks.config_dir }} \
                          --build-dir ${{ matrix.stacks.output_dir }}

    # TODO remove before PR
    - name: Tree
      run: tree .

    - name: Generate Package Receipts
      id: receipts
      run: |
        scripts/receipts.sh --build-image "${{ matrix.stacks.output_dir }}/build.oci" \
                            --run-image "${{ matrix.stacks.output_dir }}/run.oci" \
                            --build-receipt current-build-receipt-${{ matrix.stacks.name }} \
                            --run-receipt current-run-receipt-${{ matrix.stacks.name }}
        echo "build_receipt=current-build-receipt-${{ matrix.stacks.name }}" >> "$GITHUB_OUTPUT"
        echo "run_receipt=current-run-receipt-${{ matrix.stacks.name }}" >> "$GITHUB_OUTPUT"

    # TODO remove before PR
    - name: Tree
      run: tree .

    - name: Upload run image
      uses: actions/upload-artifact@v4
      with:
        name: current-run-image-${{ matrix.stacks.name }}
        path: "${{ matrix.stacks.output_dir }}/run.oci"
        if-no-files-found: error 

    - name: Upload build image
      if: ${{ matrix.stacks.create_build_image == true }}
      uses: actions/upload-artifact@v4
      with:
        name: current-build-image-${{ matrix.stacks.name }}
        path: "${{ matrix.stacks.output_dir }}/build.oci"
        if-no-files-found: error 

    - name: Upload Build receipt
      if: ${{ matrix.stacks.create_build_image == true }}
      uses: actions/upload-artifact@v4
      with:
        name: current-build-receipt-${{ matrix.stacks.name }}
        path: ${{ steps.receipts.outputs.build_receipt }}
        if-no-files-found: error 

    - name: Upload Run receipt
      uses: actions/upload-artifact@v4
      with:
        name: current-run-receipt-${{ matrix.stacks.name }}
        path: ${{ steps.receipts.outputs.run_receipt }}
        if-no-files-found: error 

  test:
    name: Acceptance Test
    needs: [ create_stack, preparation ]
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Download Build images
      uses: actions/download-artifact@v4
      with:
        pattern: |
           current-build-image-*
    
    - name: Download Run images
      uses: actions/download-artifact@v4
      with:
        pattern: |
           current-run-image-*

    - name: Treeeee
      run: tree .

    - name: Create OCI artifacts destination directory
      run: |
        echo '${{ needs.preparation.outputs.stacks }}' | jq -c '.[]' | while read -r stack; do
          name=$(echo "$stack" | jq -r '.name')
          output_dir=$(echo "$stack" | jq -r '.output_dir')
          create_build_image=$(echo "$stack" | jq -r '.create_build_image')
          mkdir $output_dir
          mv "current-run-image-${name}/run.oci" "${output_dir}/run.oci"
          if [ $create_build_image == 'true' ]; then
            mv "current-build-image-${name}/build.oci" "${output_dir}/build.oci"
          fi
        done

    # TODO put the actual code back before PR
    # - name: Run Acceptance Tests
    #   run: ./scripts/test.sh

    - name: Run Acceptance Tests
      run: echo "skipped for testing purposes"

  force_release_creation:
    name: Force Release Creation
    runs-on: ubuntu-22.04
    if: ${{github.event.inputs.force == 'true'}}
    steps:
    - name: Signal force release creation
      run: |
        echo "Force release creation input set to true"

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: [create_stack, run_if_stack_files_changed, test, force_release_creation, preparation]
    if: ${{ always() && needs.test.result == 'success' && ( needs.run_if_stack_files_changed.result == 'success' || needs.force_release_creation.result == 'success' ) }}
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
    - name: Print Release Reasoning
      run: |
        printf "Acceptance Tests: %s\n" "${{ needs.test.result }}"
        printf "Force Release: %s\n" "${{ github.event.inputs.force }}"

    - name: Checkout With History
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # gets full history

    - name: Increment Tag
      if: github.event.inputs.version == ''
      id: semver
      uses: paketo-buildpacks/github-config/actions/tag/increment-tag@main
      with:
        allow_head_tagged: true

    - name: Set Release Tag
      id: tag
      run: |
        tag="${{ github.event.inputs.version }}"
        if [ -z "${tag}" ]; then
          tag="${{ steps.semver.outputs.tag }}"
        fi
        echo "tag=${tag}" >> "$GITHUB_OUTPUT"

    - name: Get Repository Name
      id: repo_name
      run: |
        full=${{ github.repository }}
        # Strip off the org and slash from repo name
        # paketo-buildpacks/jammy-base-stack --> jammy-base-stack
        repo=$(echo "${full}" | sed 's/^.*\///')
        echo "github_repo_name=${repo}" >> "$GITHUB_OUTPUT"
        # Strip off 'stack' suffix from repo name
        # paketo-buildpacks/jammy-base-stack --> jammy-base
        registry_repo="${repo//-stack/}"
        echo "registry_repo_name=${registry_repo}" >> "$GITHUB_OUTPUT"

    - name: Create Release Notes
      id: notes
      uses: pacostas/github-config/actions/stack/release-notes@create-release-reusable
      with:
        build_image: "${{ needs.preparation.outputs.repo_owner }}/${{ matrix.stacks.build_image }}-${{ needs.preparation.outputs.registry_repo_name }}:${{ steps.tag.outputs.tag }}"
        run_image: "${{ needs.preparation.outputs.repo_owner }}/${{ matrix.stacks.run_image }}-${{ needs.preparation.outputs.registry_repo_name }}:${{ steps.tag.outputs.tag }}"
        build_packages_added: ${{ needs.diff.outputs.build_added }}
        build_packages_modified: ${{ needs.diff.outputs.build_modified }}
        build_packages_removed_with_force: ${{ needs.diff.outputs.build_removed_with_force }}
        run_packages_added: ${{ needs.diff.outputs.run_added }}
        run_packages_modified: ${{ needs.diff.outputs.run_modified }}
        run_packages_removed_with_force: ${{ needs.diff.outputs.run_removed_with_force }}
        patched_usns: ${{ steps.poll_ubi_images.outputs.usns }}

# TODO test below step
    - name: Setup Release Assets
      id: assets
      run: |
        assets="$(jq --null-input --compact-output \
          --arg tag "${{ steps.tag.outputs.tag }}" \
          --arg repo "${{ steps.repo_name.outputs.github_repo_name }}" \
          '[
            {
              "path": ("current-build-image-${{ matrix.stacks.name }}/build" + ".oci"),
              "name": ($repo + "-" + $tag + "-" + "${{ matrix.stacks.build_image }}.oci"),
              "content_type": "application/gzip"
            },
            {
              "path": ("current-run-image-${{ matrix.stacks.name }}/run" + ".oci"),
              "name": ($repo + "-" + $tag + "-" + "${{ matrix.stacks.run_image }}.oci"),
              "content_type": "application/gzip"
            }]')"

        # Exclude/filter the assets that are not required for the release.
          if [ "${{ matrix.stacks.create_build_image }}" == "false" ]; then
          assets=$(jq -c --arg stack_name "${{ matrix.stacks.name }}" '
            .[] 
            | select(
                .path 
                | (contains("current-build-image-" + $stack_name + "/build.oci"))
                | not
            )' <<< "$assets")
        fi

        echo "${assets}" > ${{ matrix.stacks.name }}-release-assets

    - name: Save release notes
      id: save_notes
      run: |
        echo '${{ steps.notes.outputs.release_body }}' > ${{ matrix.stacks.name }}-release-body

    - name: Upload release notes of ${{ matrix.stacks.name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.stacks.name }}-release-body
        path: ${{ matrix.stacks.name }}-release-body

    - name: Upload release assets of ${{ matrix.stacks.name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.stacks.name }}-release-assets
        path: ${{ matrix.stacks.name }}-release-assets

# TODO Sync with Michael about the always() function, remove this comment before PR
  create_release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs: release
    if: ${{ always() && needs.release.result == 'success' }}
    steps:
    - name: download release assets
      uses: actions/download-artifact@v4
      with:
        pattern: |
           *-release-assets
        merge-multiple: true

    - name: Merge release assets
      id: merge_release_assets
      run: |
        merged_release_assets='[]'
        for file in *-release-assets; do
          merged_release_assets=$(jq -s add "$file" <(echo "$merged_release_assets") | jq -c)
        done

        printf "assets=$merged_release_assets" >> "$GITHUB_OUTPUT"

    - name: download release bodies
      uses: actions/download-artifact@v4
      with:
        pattern: |
           *-release-body
        merge-multiple: true

    - name: Merge release bodies
      id: merge_release_bodies
      run: |
        release_body=""
        for filename in *-release-body; do
          if [[ -n "$release_body" ]]; then
            release_body+=$'\n'
          fi
          release_body+=$(cat "$filename")
        done

        json_release_body=$(jq -c -n --arg content "$release_body" '{text: $content}')

        echo "release_body=$json_release_body" >> $GITHUB_OUTPUT

    - name: Download current build images
      uses: actions/download-artifact@v4
      with:
        pattern: current-build-image-*

    - name: Download current run images
      uses: actions/download-artifact@v4
      with:
        pattern: current-run-image-*

    # TODO remove before pr
    - name: Treee
      run: tree .

    - name: Create Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: v${{ needs.release.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: v${{ needs.release.outputs.tag }}
        body: ${{ fromJson(steps.merge_release_bodies.outputs.release_body).text }}
        draft: false
        assets: ${{ steps.merge_release_assets.outputs.assets }}


  failure:
    name: Alert on Failure
    runs-on: ubuntu-22.04
    needs: [create_stack, test, release, create_release]
    if: ${{ always() && needs.create_stack.result == 'failure' || needs.test.result == 'failure' || needs.release.result == 'failure' || needs.create_release.result == 'failure' }}
    steps:
      - name: File Failure Alert Issue
        uses: paketo-buildpacks/github-config/actions/issue/file@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          label: "failure:release"
          comment_if_exists: true
          issue_title: "Failure: Create Release workflow"
          issue_body: |
            Create Release workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
            Unable to update ubi images.
          comment_body: |
            Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
