name: Create Release

## TODO check if somehow we can write tests

on:
# Removing below code only for debugging purposes
  # schedule:
  # - cron: '27 2,14 * * *' # daily at 02:27 and 14:27 UTC
  # push:
  #   branches:
  #   - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release to cut (e.g. 1.2.3). No leading v'
        required: false
      force:
        description: 'Release stack even if change validator does not detect changes, or a package is removed'
        required: true
        type: choice
        default: 'false'
        options:
        - 'true'
        - 'false'

concurrency: release
env:
  RECEIPT_FILENAME_SUFFIX: "receipt.cyclonedx.json"
jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-22.04
    outputs:
      stacks: ${{ steps.get-stack-names.outputs.stacks }}
      github_repo_name: ${{ steps.repo.outputs.github_repo_name }}
      registry_repo_name: ${{ steps.repo.outputs.registry_repo_name }}
      repo_owner: ${{ steps.repo.outputs.repo_owner }}
      supports_usns: ${{ steps.supports_usns.outputs.supports_usns }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get stack names
        id: get-stack-names
        run: |
          default_stacks=$(
            cat <<EOF
          [
            {
              "name": "stack",
              "config_dir": "stack",
              "output_dir": "build",
              "build_image": "build",
              "build_receipt_filename": "build",
              "run_image": "run",
              "run_receipt_filename": "run",
              "patched_usns_filename_suffix": "patched-usns.json"
            }
          ]
          EOF
          )

          stacks_filename="images.json"

          stacks_from_file='[]'
          if [[ -f "$stacks_filename" ]]; then

            stacks_from_file=$(jq '[.[] |
            select(.name != "stack" and .config_dir != "stack" and .output_dir != "build") |
            . +
            {
              "build_image": ("build-" + .name ),
              "build_receipt_filename": ("build-" + .name),
              "run_image": ("run-" + .name ),
              "run_receipt_filename": ("run-" + .name),
              "patched_usns_filename_suffix": (.name + "-patched-usns.json")
            }]' $stacks_filename)
          fi

          stacks=$(jq -s -c 'add' <(echo $default_stacks) <(echo $stacks_from_file))
          printf "stacks=$stacks" >> "$GITHUB_OUTPUT"

      - name: Get Repository Name
        id: repo
        run: |
          full=${{ github.repository }}
          # Strip off the org and slash from repo name
          # paketo-buildpacks/jammy-base-stack --> jammy-base-stack
          repo=$(echo "${full}" | sed 's/^.*\///')
          echo "github_repo_name=${repo}" >> "$GITHUB_OUTPUT"

          # Strip off 'stack' suffix from repo name
          # paketo-buildpacks/jammy-base-stack --> jammy-base
          registry_repo="${repo//-stack/}"
          echo "registry_repo_name=${registry_repo}" >> "$GITHUB_OUTPUT"

          # translates 'paketo-buildpacks' to 'paketobuildpacks'
          repo_owner="${GITHUB_REPOSITORY_OWNER/-/}"
          printf "repo_owner=%s\n" "${repo_owner}" >> "$GITHUB_OUTPUT"

      # TODO this will have to be fetched from somewhere fromt the disk
      # and not being hardcoded
      # should this be ubi or rhel?
      - name: Get OS
        id: get_os
        run: echo "os=ubi" >> "$GITHUB_OUTPUT"

      - name: OS supports USNs
        id: supports_usns
        run: |
          if [ "${{ steps.get_os.outputs.os }}" == "ubi" ]; then
            echo "supports_usns=false" >> "$GITHUB_OUTPUT"
          else
            echo "supports_usns=true" >> "$GITHUB_OUTPUT"
          fi

  poll_usns:
    name: Poll USNs
    runs-on: ubuntu-22.04
    needs: preparation
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    outputs:
      usns: ${{ steps.convert_usn_array.outputs.usns }}
      skip: ${{ steps.skip_poll_usns.outputs.skip }}
    steps:
    - name: Check if Poll USNs should be skipped
      id: skip_poll_usns
      run: |
        if [ "${{ needs.preparation.outputs.supports_usns }}" == "true" ]; then
          echo "skip=false" >> "$GITHUB_OUTPUT"
        else
          echo "skip=true" >> "$GITHUB_OUTPUT"
          echo "usns=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Find and Download Previous Build Receipt
      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
      id: previous_build
      uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
      with:
        asset_pattern: "${{ matrix.stacks.build_image }}-${{ env.RECEIPT_FILENAME_SUFFIX }}"
        search_depth: 1
        repo: ${{ github.repository }}
        output_path: "/github/workspace/${{ matrix.stacks.build_image }}-${{ env.RECEIPT_FILENAME_SUFFIX }}"
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        strict: true

    - name: Find and Download Previous Run Receipt
      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
      id: previous_run
      uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
      with:
        asset_pattern: "${{ matrix.stacks.run_image }}-${{ env.RECEIPT_FILENAME_SUFFIX }}"
        search_depth: 1
        repo: ${{ github.repository }}
        output_path: "/github/workspace/${{ matrix.stacks.run_image }}-${{ env.RECEIPT_FILENAME_SUFFIX }}"
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        strict: true

    # TODO remove before PR
    - name: Treee
      run: tree .

    - name: Get Package List
      id: packages
      if: >- 
        ${{
          steps.skip_poll_usns.outputs.skip == 'false' &&
          steps.previous_build.outputs.output_path != '' && steps.previous_run.outputs.output_path != '' 
        }}
      uses: paketo-buildpacks/github-config/actions/stack/generate-package-list@main
      with:
        build_receipt: "${{ github.workspace }}/${{ matrix.stacks.build_image }}-${{ env.RECEIPT_FILENAME_SUFFIX }}"
        run_receipt: "${{ github.workspace }}/${{ matrix.stacks.run_image }}-${{ env.RECEIPT_FILENAME_SUFFIX }}"

    - name: Find and Download Previous Patched USNs
      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
      id: download_patched
      uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
      with:
        asset_pattern: "${{ needs.prepration.outputs.github_repo_name }}-[0-9]+.[0-9]+.[0-9]+-${{ matrix.stacks.patched_usns_filename_suffix }}"
        search_depth: "-1"   # Search all releases
        repo: ${{ github.repository }}
        output_path: "/github/workspace/${{ matrix.stacks.patched_usns_filename_suffix }}"
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

    # TODO test with USNs
    - name: Output Patched USNs as JSON String
      id: patched
      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' && steps.download_patched.outputs.output_path != '' }}
      run: |
        patched=$(jq --compact-output . < "${GITHUB_WORKSPACE}/${{ matrix.stacks.patched_usns_filename_suffix }}")
        printf "patched=%s\n" "${patched}" >> "$GITHUB_OUTPUT"

    - name: Get Stack Distribution Name
      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
      id: distro
      run: |
        # Extract distro from repo name:
        # paketo-buildpacks/jammy-tiny-stack --> jammy
        distro="$(echo "${{ github.repository }}" | sed 's/^.*\///' | sed 's/\-.*$//')"
        echo "Ubuntu distribution: ${distro}"
        printf "distro=%s\n" "${distro}" >> "$GITHUB_OUTPUT"

    - name: Get New USNs
      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
      id: usns
      uses: paketo-buildpacks/github-config/actions/stack/get-usns@main
      with:
        distribution: ${{ steps.distro.outputs.distro }}
        packages: ${{ steps.packages.outputs.packages }}
        last_usns: ${{ steps.patched.outputs.patched }}

    - name: Store New USNs
      run: |
        # We have to create a directory to store the new usns,
        # otherwise we get a permission denied error
        mkdir -p new-usns

        if [ "${{ steps.skip_poll_usns.outputs.skip }}" == "true" ]; then
          echo '[]' > new-usns/${{ matrix.stacks.patched_usns_filename_suffix }}
        else
          echo '${{ steps.usns.outputs.usns }}' > new-usns/${{ matrix.stacks.patched_usns_filename_suffix }}
        fi


    # TODO remove before PR
    - name: Treeeee
      run: tree .

    - name: Upload new USNs 
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.stacks.patched_usns_filename_suffix }}
        path: new-usns/${{ matrix.stacks.patched_usns_filename_suffix }}

    - name: Convert usn array to boolean
      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
      id: convert_usn_array
      run: |
        # We convert the array to a boolean as the usns are stored on a file 
        # we dont need to store it on the output
        if [ "${{ steps.usns.outputs.usns }}" != '[]' ]; then 
        echo "usns=true" >> "$GITHUB_OUTPUT"
        fi

  stack_files_changed:
    name: Determine If Stack Files Changed
    runs-on: ubuntu-22.04
    needs: poll_usns 
    if: >- 
      ${{
        ( ! ( needs.poll_usns.outputs.usns == 'true' && github.event_name == 'schedule' ) )
        ||
        ( ! ( github.event_name == 'schedule' ) && needs.poll_usns.outputs.skip == 'true' ) 
      }}
    outputs:
      stack_files_changed: ${{ steps.compare.outputs.stack_files_changed }}
    steps:
    - name: Checkout With History
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # gets full history

    - name: Compare With Previous Release
      id: compare
      run: |
        # shellcheck disable=SC2046
        changed="$(git diff --name-only $(git describe --tags --abbrev=0) -- ${{ matrix.stacks.name }})"
        if [ -n "${changed}" ]
        then
          echo "Relevant files of ${{ matrix.stacks.name }}, have changed since previous release."
          echo "${changed}"
          echo "stack_files_changed=true" >> "$GITHUB_OUTPUT"
        fi

  run_if_stack_files_changed:
    name: Run If Stack Files Changed
    runs-on: ubuntu-22.04
    needs: [stack_files_changed]
    if: ${{ needs.stack_files_changed.outputs.stack_files_changed == 'true' }}
    steps:
    - name: Run if stack files changed
      run: |
        echo "stack files have changed"

  create_stack:
    name: Create Stack
    needs: [ poll_usns, preparation ] 
    if: >- 
      ${{
        ( ! ( needs.poll_usns.outputs.usns == 'true' && github.event_name == 'schedule' ) )
        ||
        ( ! ( github.event_name == 'schedule' ) && needs.poll_usns.outputs.skip == 'true' ) 
      }}
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # TODO remove before PR
    - name: Tree
      run: tree .

    - name: Create ${{ matrix.stacks.name }}
      id: create-stack
      run: |
        scripts/create.sh --stack-dir ${{ matrix.stacks.config_dir }} \
                          --build-dir ${{ matrix.stacks.output_dir }}

    # TODO remove before PR
    - name: Tree
      run: tree .

    - name: Generate Package Receipts
      id: receipts
      run: |
        scripts/receipts.sh --build-image "${{ matrix.stacks.output_dir }}/build.oci" \
                            --run-image "${{ matrix.stacks.output_dir }}/run.oci" \
                            --build-receipt current-build-receipt-${{ matrix.stacks.name }} \
                            --run-receipt current-run-receipt-${{ matrix.stacks.name }}
        echo "build_receipt=current-build-receipt-${{ matrix.stacks.name }}" >> "$GITHUB_OUTPUT"
        echo "run_receipt=current-run-receipt-${{ matrix.stacks.name }}" >> "$GITHUB_OUTPUT"

    # TODO remove before PR
    - name: Tree
      run: tree .

    - name: Upload run image
      uses: actions/upload-artifact@v4
      with:
        name: current-run-image-${{ matrix.stacks.name }}
        path: "${{ matrix.stacks.output_dir }}/run.oci"
        if-no-files-found: error 

    - name: Upload build image
      uses: actions/upload-artifact@v4
      with:
        name: current-build-image-${{ matrix.stacks.name }}
        path: "${{ matrix.stacks.output_dir }}/build.oci"
        if-no-files-found: error 

    - name: Upload Build receipt
      uses: actions/upload-artifact@v4
      with:
        name: current-build-receipt-${{ matrix.stacks.name }}
        path: ${{ steps.receipts.outputs.build_receipt }}
        if-no-files-found: error 

    - name: Upload Run receipt
      uses: actions/upload-artifact@v4
      with:
        name: current-run-receipt-${{ matrix.stacks.name }}
        path: ${{ steps.receipts.outputs.run_receipt }}
        if-no-files-found: error 

  diff:
    name: Diff Packages
    outputs:
      removed_with_force: ${{ steps.removed_with_force.outputs.packages_removed }}
    needs: [ create_stack, preparation ]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    steps:
    - name: Download Build Receipt
      uses: actions/download-artifact@v4
      with:
        name: current-build-receipt-${{ matrix.stacks.name }}

    - name: Download Run Receipt
      uses: actions/download-artifact@v4
      with:
        name: current-run-receipt-${{ matrix.stacks.name }}

    - name: Check for Previous Releases
      id: check_previous
      run: |
        gh auth status
        # shellcheck disable=SC2046
        if [ $(gh api "/repos/${{ github.repository }}/releases" | jq -r 'length') -eq 0 ]; then
          echo "exists=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        echo "exists=true" >> "$GITHUB_OUTPUT"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Write Empty Previous Receipts
      if: ${{ steps.check_previous.outputs.exists == 'false' }}
      run: |
        echo '{"components":[]}' > "${{ github.workspace }}/previous-build-receipt-${{ matrix.stacks.name }}"
        echo '{"components":[]}' > "${{ github.workspace }}/previous-run-receipt-${{ matrix.stacks.name }}"

    # TODO remove before PR
    - name: Treee
      run: tree .

    - name: Find and Download Previous Build Receipt
      if: ${{ steps.check_previous.outputs.exists == 'true' }}
      uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
      with:
        asset_pattern: "${{ matrix.stacks.build_image }}-${{ env.RECEIPT_FILENAME_SUFFIX}}"
        search_depth: 1
        repo: ${{ github.repository }}
        output_path: "/github/workspace/previous-build-receipt-${{ matrix.stacks.name }}"
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        strict: true

    - name: Find and Download Previous Run Receipt
      if: ${{ steps.check_previous.outputs.exists == 'true' }}
      uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
      with:
        asset_pattern: "${{ matrix.stacks.run_image }}-${{ env.RECEIPT_FILENAME_SUFFIX}}"
        search_depth: 1
        repo: ${{ github.repository }}
        output_path: "/github/workspace/previous-run-receipt-${{ matrix.stacks.name }}"
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        strict: true
    
    # TODO remove before PR 
    - name: Treee
      run: tree .

    - name: Compare Build Packages
      id: build_diff
      uses: paketo-buildpacks/github-config/actions/stack/diff-package-receipts@main
      with:
        previous: "/github/workspace/previous-build-receipt-${{ matrix.stacks.name }}"
        current: "/github/workspace/current-build-receipt-${{ matrix.stacks.name }}"

    - name: Compare Run Packages
      id: run_diff
      uses: paketo-buildpacks/github-config/actions/stack/diff-package-receipts@main
      with:
        previous: "/github/workspace/previous-run-receipt-${{ matrix.stacks.name }}"
        current: "/github/workspace/current-run-receipt-${{ matrix.stacks.name }}"

    - name: Fail If Packages Removed
      id: removed_with_force
      env:
        BUILD_REMOVED: ${{ steps.build_diff.outputs.removed }}
        RUN_REMOVED: ${{ steps.run_diff.outputs.removed }}
      run: |
         build=$(jq '. | length' <<< "${BUILD_REMOVED}")
         echo "Build packages removed: ${build}"

         run=$(jq '. | length' <<< "${RUN_REMOVED}")
         echo "Run packages removed: ${run}"

         # only fail if packages are removed AND the release has not been forced
         if [ "${build}" -gt 0 ] || [ "${run}" -gt 0 ]; then
           if [ "${{ github.event.inputs.force }}" != 'true' ]; then
             echo "Packages removed without authorization. Stack cannot be released."
             exit 1
           else
             echo "packages_removed=true" >> "$GITHUB_OUTPUT"
           fi
         fi

    # TODO check if there is a more nice way for below code to handle the env variables
    - name: Create/Upload variable artifacts
      id: variable_artifacts
      run: |
        mkdir -p ${{ matrix.stacks.name }}_diff_packages
        cd ${{ matrix.stacks.name }}_diff_packages
        echo "${BUILD_ADDED}" > build_added
        echo "${BUILD_MODIFIED}" > build_modified
        echo "${BUILD_REMOVED_WITH_FORCE}" > build_removed_with_force
        echo "${RUN_ADDED}" > run_added
        echo "${RUN_MODIFIED}" > run_modified
        echo "${RUN_REMOVED_WITH_FORCE}" > run_removed_with_force

    - name: Upload ${{ matrix.stacks.name }}_diff_packages
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.stacks.name }}_diff_packages
        path: ${{ matrix.stacks.name }}_diff_packages

  run_if_packages_removed_with_force:
    name: Run If Packages Removed With Force
    needs: [ diff ]
    runs-on: ubuntu-22.04
    if: ${{ needs.diff.outputs.removed_with_force == 'true' }}
    steps:
    - name: Run if packages removed with force
      run: |
        echo "packages removed with user-provided force"

  packages_changed:
    name: Determine If Packages Changed
    needs: [ diff, preparation ]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    outputs:
      packages_changed: ${{ steps.compare.outputs.packages_changed }}
    steps:
    - name: Download ${{ matrix.stacks.name }}_diff_packages
      uses: actions/download-artifact@v4
      with:
       name: ${{ matrix.stacks.name }}_diff_packages

    - name: Create env variables
      run: |
       echo "BUILD_ADDED=$(cat ${{ matrix.stacks.name }}_build_added)" >> $GITHUB_ENV
       echo "BUILD_MODIFIED=$(cat ${{ matrix.stacks.name }}_build_modified)" >> $GITHUB_ENV
       echo "RUN_ADDED=$(cat ${{ matrix.stacks.name }}_run_added)" >> $GITHUB_ENV
       echo "RUN_MODIFIED=$(cat ${{ matrix.stacks.name }}_run_modified)" >> $GITHUB_ENV

    - name: Compare With Previous Release
      id: compare
      run: |
        # shellcheck disable=SC2153
        build_added=$(jq '. | length' <<< "${BUILD_ADDED}")
        echo "Build packages added: ${build_added}"

        # shellcheck disable=SC2153
        build_modified=$(jq '. | length' <<< "${BUILD_MODIFIED}")
        echo "Build packages modified: ${build_modified}"

        # shellcheck disable=SC2153
        run_added=$(jq '. | length' <<< "${RUN_ADDED}")
        echo "Run packages added: ${run_added}"

        # shellcheck disable=SC2153
        run_modified=$(jq '. | length' <<< "${RUN_MODIFIED}")
        echo "Run packages modified: ${run_modified}"

        if [ "${build_added}" -eq 0 ] && [ "${build_modified}" -eq 0 ] && [ "${run_added}" -eq 0 ] && [ "${run_modified}" -eq 0 ]; then
          echo "No packages changed."
          # we dont set the "packages_changed" to false, as is already null
          # and also due to parallelization, it will override any true value
        else
          echo "Packages changed."
          echo "packages_changed=true" >> "$GITHUB_OUTPUT"
        fi

  run_if_packages_changed:
    name: Run If Packages Changed
    runs-on: ubuntu-22.04
    needs: [packages_changed, preparation]
    if: ${{ needs.packages_changed.outputs.packages_changed == 'true' }}
    steps:
    - name: Run if packages changed
      run: |
        echo "packages have changed"

  test:
    name: Acceptance Test
    needs: [ create_stack, preparation ]
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Download Build images
      uses: actions/download-artifact@v4
      with:
        pattern: |
           current-build-image-*
    
    - name: Download Run images
      uses: actions/download-artifact@v4
      with:
        pattern: |
           current-run-image-*

    - name: Treeeee
      run: tree .

    - name: Create OCI artifacts destination directory
      run: |
        echo '${{ needs.preparation.outputs.stacks }}' | jq -c '.[]' | while read -r stack; do
          name=$(echo "$stack" | jq -r '.name')
          output_dir=$(echo "$stack" | jq -r '.output_dir')
          mkdir $output_dir
          mv "current-build-image-${name}/build.oci" "${output_dir}/build.oci"
          mv "current-run-image-${name}/run.oci" "${output_dir}/run.oci"
        done

    - name: Run Acceptance Tests
      run: ./scripts/test.sh

  force_release_creation:
    name: Force Release Creation
    runs-on: ubuntu-22.04
    if: ${{github.event.inputs.force == 'true'}}
    steps:
    - name: Signal force release creation
      run: |
        echo "Force release creation input set to true"

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: [poll_usns, create_stack, diff, run_if_stack_files_changed, run_if_packages_changed, run_if_packages_removed_with_force, test, force_release_creation, preparation ]
    if: |
      ${{ always() &&
      needs.diff.result == 'success' &&
      needs.test.result == 'success' &&
        (needs.run_if_packages_changed.result == 'success' ||
         needs.run_if_stack_files_changed.result == 'success' ||
         needs.force_release_creation.result == 'success' )
      }}
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
    - name: Print Release Reasoning
      run: |
        printf "Diff Packages: %s\n" "${{ needs.diff.result }}"
        printf "Acceptance Tests: %s\n" "${{ needs.test.result }}"
        printf "Run If Packages Changed: %s\n" "${{ needs.run_if_packages_changed.result }}"
        printf "Run If Packages Removed With Force: %s\n" "${{ needs.run_if_packages_removed_with_force.result }}"
        printf "Run If Stack Files Changed: %s\n" "${{ needs.run_if_stack_files_changed.result }}"
        printf "Force Release: %s\n" "${{ github.event.inputs.force }}"

    - name: Checkout With History
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # gets full history

    - name: Download USNs
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.stacks.patched_usns_filename_suffix }}

    - name: Get Polled USNs
      id: poll_usns
      run: |
        usns=$(cat ${{ matrix.stacks.patched_usns_filename_suffix }} )
        echo "usns=$usns" >> "$GITHUB_OUTPUT"
        rm ${{ matrix.stacks.patched_usns_filename_suffix }}

    # TODO this might has to be moved on preparation step as it might run
    # multiple parallel times and it might has to run only once.
    - name: Increment Tag
      if: github.event.inputs.version == ''
      id: semver
      uses: paketo-buildpacks/github-config/actions/tag/increment-tag@main
      with:
        allow_head_tagged: true

    - name: Set Release Tag
      id: tag
      run: |
        tag="${{ github.event.inputs.version }}"
        if [ -z "${tag}" ]; then
          tag="${{ steps.semver.outputs.tag }}"
        fi
        echo "tag=${tag}" >> "$GITHUB_OUTPUT"
        
    - name: Write USNs File
      id: write_usns
      if: ${{ steps.poll_usns.outputs.usns != '[]'  }}
      run: |
        jq . <<< "${USNS}" > "${USNS_PATH}"
        echo "usns=${USNS_PATH}" >> "$GITHUB_OUTPUT"
      env:
        USNS_PATH: "${{ matrix.stacks.patched_usns_filename_suffix }}"
        USNS: ${{ steps.poll_usns.outputs.usns }}

    - name: Get Repository Name
      id: repo_name
      run: |
        full=${{ github.repository }}
        # Strip off the org and slash from repo name
        # paketo-buildpacks/jammy-base-stack --> jammy-base-stack
        repo=$(echo "${full}" | sed 's/^.*\///')
        echo "github_repo_name=${repo}" >> "$GITHUB_OUTPUT"
        # Strip off 'stack' suffix from repo name
        # paketo-buildpacks/jammy-base-stack --> jammy-base
        registry_repo="${repo//-stack/}"
        echo "registry_repo_name=${registry_repo}" >> "$GITHUB_OUTPUT"

    - name: Create Release Notes
      id: notes
      uses: paketo-buildpacks/github-config/actions/stack/release-notes@main
      with:
        build_image: "${{ needs.preparation.outputs.repo_owner }}/${{ matrix.stacks.build_image }}-${{ needs.preparation.outputs.registry_repo_name }}:${{ steps.tag.outputs.tag }}"
        run_image: "${{ needs.preparation.outputs.repo_owner }}/${{ matrix.stacks.run_image }}-${{ needs.preparation.outputs.registry_repo_name }}:${{ steps.tag.outputs.tag }}"
        build_packages_added: ${{ needs.diff.outputs.build_added }}
        build_packages_modified: ${{ needs.diff.outputs.build_modified }}
        build_packages_removed_with_force: ${{ needs.diff.outputs.build_removed_with_force }}
        run_packages_added: ${{ needs.diff.outputs.run_added }}
        run_packages_modified: ${{ needs.diff.outputs.run_modified }}
        run_packages_removed_with_force: ${{ needs.diff.outputs.run_removed_with_force }}
        patched_usns: ${{ steps.poll_usns.outputs.usns }}

    - name: Setup Release Assets
      id: assets
      run: |
        assets="$(jq --null-input --compact-output \
          --arg tag "${{ steps.tag.outputs.tag }}" \
          --arg repo "${{ steps.repo_name.outputs.github_repo_name }}" \
          --arg build_receipt "${{ matrix.stacks.build_receipt_filename }}-${{ env.RECEIPT_FILENAME_SUFFIX }}" \
          --arg run_receipt "${{ matrix.stacks.run_receipt_filename }}-${{ env.RECEIPT_FILENAME_SUFFIX }}" \
          --arg build_receipt_path "current-build-receipt-${{ matrix.stacks.name }}" \
          --arg run_receipt_path "current-run-receipt-${{ matrix.stacks.name }}"  \
          --arg build_image_path "current-build-image-${{ matrix.stacks.name }}/build" \
          --arg run_image_path "current-run-image-${{ matrix.stacks.name }}/run" \
          '[
            {
              "path": ($build_image_path + ".oci"),
              "name": ($repo + "-" + $tag + "-" + "${{ matrix.stacks.build_image }}.oci"),
              "content_type": "application/gzip"
            },
            {
              "path": ($run_image_path + ".oci"),
              "name": ($repo + "-" + $tag + "-" + "${{ matrix.stacks.run_image }}.oci"),
              "content_type": "application/gzip"
            },
            {
              "path": ($build_receipt_path),
              "name": ($repo + "-" + $tag + "-" + $build_receipt),
              "content_type": "text/plain"
            },
            {
              "path": ($run_receipt_path),
              "name": ($repo + "-" + $tag + "-" + $run_receipt),
              "content_type": "text/plain"
            }]')"

        if [ -n "${{ steps.write_usns.outputs.usns }}" ]; then
          assets="$(jq --compact-output \
            --arg tag "${{ steps.tag.outputs.tag }}" \
            --arg repo "${{ steps.repo_name.outputs.github_repo_name }}" \
            --arg usn_path "${{ steps.write_usns.outputs.usns }}" \
            --arg usn_name "${{ matrix.stacks.patched_usns_filename_suffix }}" \
            '. += [
            {
              "path": $usn_path,
              "name": ($repo + "-" + $tag + "-" + $usn_name),
              "content_type": "text/plain"
            }
          ]' <<< "${assets}")"
        fi

        echo "${assets}" > ${{ matrix.stacks.name }}-release-assets

    - name: Save release notes
      id: save_notes
      run: |
        echo '${{ steps.notes.outputs.release_body }}' > ${{ matrix.stacks.name }}-release-body

    - name: Upload release notes of ${{ matrix.stacks.name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.stacks.name }}-release-body
        path: ${{ matrix.stacks.name }}-release-body

    - name: Upload release assets of ${{ matrix.stacks.name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.stacks.name }}-release-assets
        path: ${{ matrix.stacks.name }}-release-assets

  # TODO Sync with Michael about the always() function, remove this comment before PR
  create_release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs: release
    if: ${{ always() && needs.release.result == 'success' }}
    steps:
    - name: download release assets
      uses: actions/download-artifact@v4
      with:
        pattern: |
           *-release-assets
        merge-multiple: true

    - name: Merge release assets
      id: merge_release_assets
      run: |
        merged_release_assets='[]'
        for file in *-release-assets; do
          merged_release_assets=$(jq -s add "$file" <(echo "$merged_release_assets") | jq -c)
        done

        printf "assets=$merged_release_assets" >> "$GITHUB_OUTPUT"

    - name: download release bodies
      uses: actions/download-artifact@v4
      with:
        pattern: |
           *-release-body
        merge-multiple: true

    - name: Merge release bodies
      id: merge_release_bodies
      run: |
        release_body=""
        for filename in *-release-body; do
          if [[ -n "$release_body" ]]; then
            release_body+=$'\n'
          fi
          release_body+=$(cat "$filename")
        done

        json_release_body=$(jq -c -n --arg content "$release_body" '{text: $content}')

        echo "release_body=$json_release_body" >> $GITHUB_OUTPUT

    - name: Download all receipts and patched USNs
      uses: actions/download-artifact@v4
      with:
        pattern: |
           *patched-usns.json
        merge-multiple: true

    - name: Download current buil images
      uses: actions/download-artifact@v4
      with:
        pattern: current-build-image-*

    - name: Download current run images
      uses: actions/download-artifact@v4
      with:
        pattern: current-run-image-*

    - name: Download Build Receipts
      uses: actions/download-artifact@v4
      with:
        pattern: current-build-receipt-*
        merge-multiple: true

    - name: Download Run Receipts
      uses: actions/download-artifact@v4
      with:
        pattern: current-run-receipt-*
        merge-multiple: true

    - name: Treee
      run: tree .

    - name: Create Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: v${{ needs.release.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: v${{ needs.release.outputs.tag }}
        body: ${{ fromJson(steps.merge_release_bodies.outputs.release_body).text }}
        draft: false
        assets: ${{ steps.merge_release_assets.outputs.assets }}

  # Probably i need to add the new jobs that i craeted to be on the if statement
  failure:
    name: Alert on Failure
    runs-on: ubuntu-22.04
    needs: [poll_usns, create_stack, diff, test, release, create_release, packages_changed, stack_files_changed]
    if: ${{ always() && needs.poll_usns.result == 'failure' || needs.create_stack.result == 'failure' || needs.diff.result == 'failure' || needs.test.result == 'failure' || needs.release.result == 'failure' || needs.packages_changed.result == 'failure' || needs.stack_files_changed.result == 'failure' }}
    steps:
    - name: File Failure Alert Issue
      uses: paketo-buildpacks/github-config/actions/issue/file@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: ${{ github.repository }}
        label: "failure:release"
        comment_if_exists: true
        issue_title: "Failure: Create Release workflow"
        issue_body: |
          Create Release workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
          Please take a look to ensure CVE patches can be released. (cc @paketo-buildpacks/stacks-maintainers).
        comment_body: |
          Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
